server:
  port: 9093

eureka:
 client:
   service-url:
      defaultZone:  http://localhost:9090/eureka/
spring:
  application:
    name: gateway
zuul:
  routes:
     service0: /service0/**
     service1: /service1/**

